# Generated by Django 4.2.3 on 2023-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(default='', max_length=5)),
                ('current_floor', models.IntegerField()),
                ('door_open', models.BooleanField(default=False)),
            ],
        ),
    ]
