# Generated by Django 4.2.3 on 2023-07-31 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_elevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=0),
        ),
    ]
