# Generated by Django 4.2.3 on 2023-07-31 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_elevator', '0002_elevator_is_created_alter_elevator_current_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('Floor_no', models.IntegerField()),
                ('elevator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_elevator.elevator')),
            ],
        ),
    ]
