# Generated by Django 4.2.3 on 2023-07-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_elevator', '0003_elevatorrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevatorrequest',
            old_name='Floor_no',
            new_name='floor_no',
        ),
    ]
