# Generated by Django 4.2.3 on 2023-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_elevator', '0004_rename_floor_no_elevatorrequest_floor_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='is_active',
        ),
        migrations.AddField(
            model_name='elevator',
            name='condition',
            field=models.CharField(default='working', max_length=56),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='direction',
            field=models.CharField(default='up', max_length=5),
        ),
    ]
